### ISSUE TITLE
"upload tracks" button too smal if language selected is german and browser is Chrome

### ISSUE THREAD

**Issue by wschildbach** [OpenSeaMap/depth_webfrontend#105]
If I select german as the language, this is how the track upload looks:

![image](https://cloud.githubusercontent.com/assets/4427008/2939581/f6318116-d94f-11e3-888e-122d5b424bbf.png)

I am using Chrome; it appears that with IE, the problem does not exist..

**Comment by cleanerx** [comment]
Fixed translation
