### ISSUE TITLE
Vessel - Schiffsname

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#111]
auf der ersten Seite steht:
"Name" und "Name der Konfiguration"
Das ist verwirrend.
Richtig ist:
"Schiffsname" und "Schiffsname"
plus zur Identifikation die entsprechend vorgesehenen Felder.

Falls es mehrere Konfigurationen für dieses Schiff gibt:
irgendetwas um die Konfigurationen zu unterscheiden
(Datum, Nummer, ...).

**Comment by cleanerx** [comment]
One can enter whatever he wants as there is no semantics tied to it. Usally one will use the ships name but that does not really matter.
