### ISSUE TITLE
Vessel - depth measurement

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#113]
auf der dritten Seite
steht als Standard "Autodetect".
Das führt zu Fehlern.

Richtig wäre, wenn der Benutzer bewusst einen Eintrag machen muss.

**Comment by ragnaroek-hh** [comment]
Wir haben mit dem Datensammeln erst vor wenigen Wochen angefangen und sind begeistert von der tollen Vorarbeit im Projekt. Vielen Dank! 

Der von nautic angesprochene Fehler hat uns einige Probleme gemacht, und hier nun unsere detailierten Erfahrungen damit:

Sowohl unter firefox 38.0 als auch IE und chrome wird auf Seite 3 unter "depth measurement" kein Eintrag übernommen, es steht nach dem Speichern immer "Autodetect" drin. (Eigentlich ein "Speicherversuch", denn der Screen bleibt ausgegraut, siehe bug #110.) Es ergibt sich folgendes falsches Verhalten:

Sowohl bei nmea DPT-Datensätzen als auch bei DBT-Datensätzen wird der fürs Vessel auf Seite 3 eingestellte Transducer Offset (Einbautiefe) NICHT übernommen. Diesen Fehler sieht man im Zoom des Track Viewer, wenn die tatsächlich übernommenen Tiefen dargestellt werden.

Beim DPT-Datensatz wird der als zweiter Parameter (hinter der Tiefenangabe) übergebene Transducer-Offset ebenfalls ignoriert. Auch ein Fehler.

Abhilfe: die Tiefen-Datensätze vor dem upload per script korrigieren, also den Tiefenparameter im DPT-Datensatz um den Transducer-Offset erhöhen, neue Parity berechnen.

Da auf vielen Seglern die "Wassertiefe unter Kiel" angezeigt werden soll, wäre dies für viele Datensammler eine unnötige Barriere.

Falls es also keinen einfacheren Weg gibt, sollte zumindest beschrieben werden, dass der Transducer-Offset ignoriert wird und die DBT/DPT-Datensätze ausschließlich "Tiefe unter Wasserlinie"  enthalten müssen.

Oder gibt es einen einfacheren Weg, "Wassertiefen unter Kiel" zu sammeln?

**Comment by cleanerx** [comment]
Ich sehe mir das mal mit der Übernahme an. Eventuell steht der Wert doch richtig in der Datenbank.
Das die Oberfläche nicht gesetzt wird, müssen wir beheben.

Das ungefilterte Rendering zeigt die Tiefen immer im Rohzustand ohne Korrekturen. Das erleichtert die Fehlersuche. Nur der Gefilterte View (100m) zeigt eventuelle Korrekturen an.
![differentlayer](https://cloud.githubusercontent.com/assets/4538270/8334848/5da8f3ba-1a9a-11e5-87a1-f7f4097b2d1f.png)

**Comment by cleanerx** [comment]
Fixed

**Comment by ragnaroek-hh** [comment]
Wäre es dann nicht für die Zukunft hilfreich, den "100m Filter 2" mit einem mouseover-text "Tiefenkorrigiert" zu versehen?

Ich habe in vessel 323 eine Sensor-Tiefe von 2.04m eingestellt. Meine zwei Testpunkte (s.u.)  werden im Filter nur ohne Korrekturen angezeigt. Dies ist ein Fehler, sowohl für DBT als auch für DPT.

Weiter ist mir aufgefallen, dass im Filter auch die gelöschten (fehlerhaften) Tracks weiter angezeigt werden. Es wäre ein Fehler, wenn diese Daten weiter genutzt werden würden.

Könntest Du das noch einmal überprüfen?  Tracks 26738 (DPT) und 26739 (DBT).

**Comment by cleanerx** [comment]
Wir sind noch in der Erprobungsphase, wo wir verschiedene Filter ausprobieren wollen. Dort kann es sein, dass wir noch einzelne Korrekturen weglassen, um das Ergebnis besser zu analysieren.

Ich habe gestern nur die Oberflächenlogik und den Server angepasst aber noch nicht das Backend, was diese Daten auswertet.
Das löschen sollte natürlich funktionieren. Kannst du da einen neuen Issue zu erstellen ?
Ich sehe mal nach den Tracknummern (mit etwas Zeitverzug ggf. erst nächste Woche)
