### ISSUE TITLE
Personalized tracks

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#116]
It should be possible for each skipper to:
- show all his own tracks on the chart
- show one (or more) of selected own tracks (from uploaded tracks list) on the chart
- download xy-data of a selected own track (GPX, CSV)

Files should show day trips
with reduced data and error elimination.

**Comment by cleanerx** [comment]
Duplicate
https://github.com/OpenSeaMap/depth_webfrontend/issues/14
