### ISSUE TITLE
Meta-Formular: "Pegel des Wasserspiegels binnen" fehlt

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#117]
http://forum.openseamap.org/viewtopic.php?pid=2888#p2888
http://wiki.openseamap.org/wiki/OpenSeaMap-dev:De:Depth_meta_data
"Pegel des Wasserspiegels binnen"

**Comment by cleanerx** [comment]
Duplicate
https://github.com/OpenSeaMap/depth_webfrontend/issues/21
