### ISSUE TITLE
Hintergrundkarte fehlt

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#118]
Ein Benutzer schreibt:
"Ich kann auf http://depth.openseamap.org/#maptracks
zwar die Tracks als rote und grüne Punkte von den anderen sehen,
jedoch fehlt in allen Zoomstufen die Hintergrundkarte zur Orientierung."

**Comment by cleanerx** [comment]
If openseamap is offline you won't see tiles.
