### ISSUE TITLE
Doubling of upload files

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#119]
Ein Benutzer schreibt:
"Merkwürdigerweise haben sich meine Uploads "vervielfältigt." 
Die gleichen Trackdateien sind jetzt mehrfach sichtbar."

**Comment by aAXEe** [comment]
Kann ich bestätigen:
![bildschirmfoto vom 2015-04-14 16 57 46](https://cloud.githubusercontent.com/assets/3298652/7139674/bdee17ec-e2c7-11e4-9bdb-b4dcb7e5afba.png)

Meinen Untersuchungen nach könnte  es sich um eine Race Condition im JavaScript handeln: 
Die JSON Antwort von http://depth.openseamap.org:8080/org.osm.depth.upload/api2/track ist korrekt:
```json
[{"id":26146,"fileName":"Tracks.gpx","upload_state":6,"fileType":"application/x-gpx","vesselconfigid"
:312,"containertrack":0,"license":1,"uploadDate":1428782825632},
{"id":26147,"fileName":"Track5-2015-04-14
.gpx","upload_state":1,"vesselconfigid":312,"containertrack":0,"license":1,"uploadDate":1429023291786
}]
```

Wenn ich mit dem Debugger rangehe, sehe ich mal mehr und mal weniger Einträge.
Allerdings kenne ich mich mit dem verwendeten Framework nicht aus. Vom Draufschauen würde ich tippen, dass etwas mit der Behandlung der Trackliste schiefgeht.
Vlt wichtig: Wenn ich die Liste sortiere (auf eine Überschrift klicke), erscheint die Liste korrekt (ohne doppelte Einträge).

**Comment by cleanerx** [comment]
I haven't seen this on my own desk yet, but I'm sure that the server provides correct data, so I'd be happy to have a clue where this is comming from. Which browser was used?

**Comment by aAXEe** [comment]
Yes the server data lloks good.
I can see this problem under Ubuntu 64 bit with Firefox 37.0.1 and Chromium Version 41.0.2272.76 Ubuntu 14.04 (64-bit)

**Comment by Nautic** [comment]
Den Bug hatte ich auch. Win 8, FF.

Da es leider nicht möglich ist, gleichzeitig die Liste der hochgeladenen Dateien serverseitig in depth und die  Liste der Dateien clientseitig im lokalen Dateimanager so zu sehen, dass man in /beiden/ abwechselnd scrollen kann, ist ein Vergleich von Ist und Soll nicht möglich.

Wenn ein einseitig serverseitiger Vergleich nach Sortieren der Dateinamen den Bug verschwinden lässt, ist es bei einer Dateimenge von mehr als 1 Bildschirmseite, vermutlich auch nicht möglich, den Bug zu sehen.
Nach Dateiname sortiert sehe ich viele Doubletten.
Bei diesen ist eine Datei als "processed" gekennzeichnet, die anderen als "::unknown::" (was auch immer letzteres bedeutet http://wiki.openseamap.org/wiki/OpenSeaMap-dev:De:Depth_upload#Liste_der_bisher_hochgeladenen_Dateien)
Die anderen sind als "Duplicate" markiert.

Der Bug besteht aber darin, dass Dateien mehrfach angezeigt werden, ohne dass sie mehrfach auf dem Server existieren.

**Comment by aAXEe** [comment]
Ist das Problem mit der doppelten Darstellung mit meinem Commit gelöst?
Zum Testen: ruft http://osm.brasshack.de/#tracks auf. Seht ihr 5 Tracks, davon 2 processed und 3 mit "upload done" Status?

**Comment by Nautic** [comment]
Hallo Axel,

> Ist das Problem mit der doppelten Darstellung mit meinem Commit gelöst?

Ich sehe:
5 Tracks, davon 2 processed und 3 mit "upload done" Status :-)

- - - -

In meinen eigenen selbst auf depth.openseamap hochgeladenen Dateien
werden Duplikate erkannt und markiert:
168 	19131_111_11_513_07-02-2013_10-56-11.XML 	Processed
7387 	19131_111_11_513_07-02-2013_10-56-11.XML 	Duplicate

Ob der Dateiname oder der Inhalt geprüft wird weiss ich nicht.

- - - -

Es gibt auch Dateien die sowohl korrupt als auch processed sind:
4084 	19131_111_11_612_07-02-2013_08-25-48.XML 	File Corrupt
8210 	19131_111_11_612_07-02-2013_08-25-48.XML 	Processed

Eigentlich dürfte die Datei nicht korrupt sein.
Vermutlich hatte ich dann "auf Gut Glück" die Datei
noch ein 2. Mal hochgeladen, und dann hat es irgendwie gepasst?
Da ich sie zwischendurch nicht geändert habe, habe ich ja die selbe 
Datei hochgeladen - misteriös...

- - - -

Viele Dateien haben den Status "::unknown::"
7848 	19132_111_13_1559_26-02-2013_11-29-27.XML 	::unknown:: 	

Es handelt sich dabei aber um das gleiche Format, das meistens den 
Status "processed" bekommt.

- - - -

Einige Dateien haben den Status "No usable data"
91 	NMEA_20130305_152425.183.gz 	No usable data

- - - -

Siehe auch: https://github.com/OpenSeaMap/depth_webfrontend/issues/136

Gruss, Markus

**Comment by cleanerx** [comment]
I ve never seen this problem on my computer and the fix did not break anything so i merged it. i suggest to close the issue and reopen it if someone reports it again

**Comment by aAXEe** [comment]
Yes I will close this issue. I think it is fixed. Please reopen it if you see a file with the SAME id in the track list multiple times.
The patterns Markus showed in the above comment have different ids. So that this is not a problem in the frontend.
