### ISSUE TITLE
Hochgeladene und vorhandene Dateien lassen sich nicht vergleichen

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#133]
Wenn man in http://depth.openseamap.org/#tracks
den clientseitigen Dateimanager öffnet, hat dieser den Fokus und gibt ihn nicht wieder her.

Dadurch ist es nicht möglich, in der serverseitigen Dateiliste zu scrollen.
Dadurch ist es nicht möglich, die beiden Listen zu vergleichen.
Es ist auch nicht möglich, die beiden Listen vergleichend zu bearbeiten.

Ein Vergleich von Ist und Soll ist so nicht möglich.

**Comment by cleanerx** [comment]
You can open up a second browser window
