### ISSUE TITLE
JS: collection.fetch() is used for synchronous requests

### ISSUE THREAD

**Issue by aAXEe** [OpenSeaMap/depth_webfrontend#137]
In src/js/oseam-views-tracks.js:
```javascript
initialize : function() {
  [...]
  this.collection.fetch({wait:true});
  [...]
}
```
This works not (always) as expacted: fetch is an asychonous operation and can not be used to wait until the data is received. This manifests sometimes on my computer: the lists for the license or ships are empty.

From the backbone manual (http://backbonejs.org/#Collection-fetch)
> Note that fetch should not be used to populate collections on page load 

Another example and a possible solution: http://stackoverflow.com/questions/11842090/backbone-fetch-collection-on-page-load

**Comment by cleanerx** [comment]
Any progress on the issue ?

**Comment by aAXEe** [comment]
Sorry my free time is very limitied in this weeks.
#143 is a possible solution for this. Please have a second look and some more testing at it.
I have not checked whether this kind of synchronous requests is in other files too.
