### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#155]
Ein Benutzer schreibt:
"wenn ich auf der Seite http://depth.openseamap.org Fahrzeugdaten oder Tiefendaten eingeben möchte kommt immer ein Fenster "Windows-Sicherheit" in dem Benutzername und Passwort eingegeben werden müssen. Nach Eingabe der Daten erscheint es sofort wieder. Es ist nicht möglich mich dort einzuloggen. Nur nach meiner Registrierung konnte ich die Boots Daten eingeben. Nach dem Ausloggen habe ich es nicht mehr geschafft mich wieder einzuloggen. Was mache ich den da wieder falsch?"

We need a standard process for:
- Register
- Login
- Logout
- change password
- send me a new password to my mailadress

**Comment by aAXEe** [comment]
Yes a normal login would be great. There is already a lot of code for this in this project but it is commented out. I do not know the state of this code.

For example src/js/templates/toolbar.handlebars:
* Dominik Fässler added a login form in 6b0aec6a6c0d3fabeb6771be5db26e20aabefdfb but made it invisible by style="display:none"
* Jens added comment tags around some parts of that code in b5a1d2dcf2e30cded7929d28d7552669b71c6169

So I *guess* what this form never actually worked but I am not sure.

Some more dead code from my point of view was introduced in 8b24dbd9aac82892e7b62765b6344dcc190f7832 at the users page: There is already a form to change the password but this form is inside a html comment. I can not tell you why this code is inside a comment tag and that is necessary to make this usable.

**Comment by cleanerx** [comment]
Duplicate https://github.com/OpenSeaMap/depth_webfrontend/issues/27
