### ISSUE TITLE
Data upload failed - No usable file

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#158]
Ein Benutzer aus Barcelona möchte DAT-Dateien vom Logger hochladen,
bekommt aber die Fehlermeldung "No usable file".

Die Daten stammen von Garmin-Geräten, so wie sie auf jeder Bavaria installiert sind.
Unser NMEA-0183-Logger ist am NMEA-0183-Ausgang des Plotters angeschlossen.

Der Benutzer hat mir eine Datei geschickt, die ich selber hochzuladen versuchte (ID 27045),
bekomme aber die gleiche Fehlermeldung.

Wo liegt das Problem?
Wie können wir? oder der Benutzer? es lösen?

Schwierigkeiten für den Benutzer:
* Die Fehelrmeldung ist unspezifisch, der Benutzer weiss nicht was er tun soll.
* Im Wiki ist die Fehlermeldung nicht aufgeführt: http://wiki.openseamap.org/wiki/De:NMEA-Daten_hochladen#Anzeige_der_hochgeladenen_Dateien
* Die Wiki-Seite ist auf http://depth.openseamap.org/#tracks nicht verlinkt

**Comment by cleanerx** [comment]
Die Datei enthält keine Tiefendaten. Die Oberfläche sagt genau das und liefert Detailinformationen im Tooltip
![image](https://cloud.githubusercontent.com/assets/4538270/9532994/585e1ba4-4d0f-11e5-92ea-6fd0fa591503.png)

**Comment by Nautic** [comment]
Sehr schön, die Lösung mit dem Tooltip !
Habe es mal ins Wiki aufgenommen...
