### ISSUE TITLE
Captcha errors are not handled properly in the frontend

### ISSUE THREAD

**Issue by aAXEe** [OpenSeaMap/depth_webfrontend#162]
If the user enters a captche code with the correct length (6 chars) but with the wrong content the server replies a 400 code (Bad Request). The frontend does not render a good error massage:
- register page
  The form stucks with the submit button in the "loading" state. No error message for the user.
- reset passwort page
  The page shows a error message: "Server error occured. / Unknown error. Please try again." This is ok but can be improved.

**Comment by wldlzi** [comment]
a new version of OpenSeaMap Backend is currently under development and will be released for testing within the next days at
https://testdepth.openseamap.org/static/src/local_index.html
This version is taking care of the two bugs you reported.
