### ISSUE TITLE
Torrent tracker refuses connection

### ISSUE THREAD

**Issue by IronicSven** [OpenSeaMap/depth_webfrontend#211]
The torrent tracker for the depth data sharing is refusing connections since yesterday afternoon.

http://5adbwbq4feu2urke.myfritz.net:37101/announce
No connection could be made because the target machine actively refused it.

**Comment by cleanerx** [comment]
Indeed. Machine crashed. I need to figure out a service there. Thanks for the hint.

**Comment by cleanerx** [comment]
Oh and it is back up again
