### ISSUE TITLE
UTF8 for Filenames

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#216]
Dateinamen mit Umlaut werden in der Liste der hochgeladenen Dateien falsch angezeigt.
falsch: Z�richsee
richtig: Zürichsee

**Comment by wldlzi** [comment]
The new Backend has solved this bug. It is available at https://testdepth.openseamap.org/static/src/local_index.html for further tests. It will go into production as soon as the test period has finished.
