### ISSUE TITLE
Always get processing error. Is it possible to see more details what goes wrong

### ISSUE THREAD

**Issue by marcelrv** [OpenSeaMap/depth_webfrontend#230]
I'm so far always getting an processing error when uploading files.
e.g.  track/upload: 124796

As far as I can see this is rather usual GPS and dept information. Any suggestion on what do to fix this?

sample data that errored:

note, not sure if it is related, but right after seeing the the rror message I was kicked/logged out and not able to log back in.
(I tried password reset, but that new password also was not accepted...)

```
$SDDPT,001.5,+0.1
$SDDBT,005.2,f,001.5,M,000.8,F
$GPGGA,121250.00,5258.095,N,00536.387,E,2,09,01.3,00001,M,00046,M,,*68
$GPGLL,5258.095,N,00536.387,E,121250.00,A,D*63
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSV,4,1,13,21,79,104,39,26,45,176,39,8,22,282,38,18,47,62,40*72
$GPGSV,4,2,13,27,55,284,39,16,71,236,38,20,46,120,27,10,26,154,40*76
$GPGSV,4,3,13,49,29,180,34,7,14,326,27,15,6,64,25,39,0,0,39*73
$GPGSV,4,4,13,13,3,36,*4F
$GPRMB,A,0.00,L,WPT0000 ,WPT0000 ,0000.000,N,00000.000,E,,,0000.0,V,D*6E
$GPRMC,121250.00,A,5258.095,N,00536.387,E,0000.0,0000.0,210620,,,D*53
$GPVTG,0000.0,T,0000.0,M,0000.0,N,0000.0,K,D*26
$SDDPT,001.5,+0.1
$SDDBT,005.1,f,001.5,M,000.8,F
```

**Comment by marcelrv** [comment]
![image](https://user-images.githubusercontent.com/5871213/85888723-73211680-b7ea-11ea-9ca0-ccd38820d54b.png)

**Comment by wldlzi** [comment]
Hello Marcel,

with a look to your NMEA sentens, I'm concerned the your
$SDDPT,001.5,+0.1
$SDDBT,005.2,f,001.5,M,000.8,F
are not complete and "  *checksum  " is missing at the end. 
Please check your logger to get correct NMEA sentens, and than let us know the result

regards Richard

**Comment by marcelrv** [comment]
thanks. This is how my (old) logger provices it...
As some other equipment also does not like it I do have a possibility to append the checksum info with signalK
I've loaded it now with checksum and indeed it seems to process

```
$SDDPT,001.5,+0.1*79
$SDDBT,005.2,f,001.5,M,000.8,F*0D
$GPGGA,121250.00,5258.095,N,00536.387,E,2,09,01.3,00001,M,00046,M,,*68
$GPGLL,5258.095,N,00536.387,E,121250.00,A,D*63
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSV,4,1,13,21,79,104,39,26,45,176,39,8,22,282,38,18,47,62,40*72
$GPGSV,4,2,13,27,55,284,39,16,71,236,38,20,46,120,27,10,26,154,40*76
$GPGSV,4,3,13,49,29,180,34,7,14,326,27,15,6,64,25,39,0,0,39*73
$GPGSV,4,4,13,13,3,36,*4F
$GPRMB,A,0.00,L,WPT0000 ,WPT0000 ,0000.000,N,00000.000,E,,,0000.0,V,D*6E
$GPRMC,121250.00,A,5258.095,N,00536.387,E,0000.0,0000.0,210620,,,D*53
$GPVTG,0000.0,T,0000.0,M,0000.0,N,0000.0,K,D*26
$SDDPT,001.5,+0.1*79
$SDDBT,005.1,f,001.5,M,000.8,F*0D
```

**Comment by wldlzi** [comment]
OK Marcel,

we are on the way to rework the OpenSeaMap software. Thats why I’m looking to close the issue list as good as possible.

However I’m glad, that you found neanwhile a solution yourself. I will close this issue.

Beste Grüße

Richard Kunzmann

E-Mail: ***@***.***
Tel: +49 151 1213 8687

Gesendet von Mail für Windows 10

Von: Marcel
Gesendet: Mittwoch, 19. Mai 2021 01:11
An: OpenSeaMap/depth_webfrontend
Cc: Richard; Comment
Betreff: Re: [OpenSeaMap/depth_webfrontend] Always get processing error. Is itpossible to see more details what goes wrong (#230)

thanks. This is how my (old) logger provices it...
As some other equipment also does not like it I do have a possibility to append the checksum info with signalK
I've loaded it now with checksum and indeed it seems to process
$SDDPT,001.5,+0.1*79
$SDDBT,005.2,f,001.5,M,000.8,F*0D
$GPGGA,121250.00,5258.095,N,00536.387,E,2,09,01.3,00001,M,00046,M,,*68
$GPGLL,5258.095,N,00536.387,E,121250.00,A,D*63
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSA,A,3,21,26,8,18,27,16,20,10,7,,,,02.2,01.3,01.8*09
$GPGSV,4,1,13,21,79,104,39,26,45,176,39,8,22,282,38,18,47,62,40*72
$GPGSV,4,2,13,27,55,284,39,16,71,236,38,20,46,120,27,10,26,154,40*76
$GPGSV,4,3,13,49,29,180,34,7,14,326,27,15,6,64,25,39,0,0,39*73
$GPGSV,4,4,13,13,3,36,*4F
$GPRMB,A,0.00,L,WPT0000 ,WPT0000 ,0000.000,N,00000.000,E,,,0000.0,V,D*6E
$GPRMC,121250.00,A,5258.095,N,00536.387,E,0000.0,0000.0,210620,,,D*53
$GPVTG,0000.0,T,0000.0,M,0000.0,N,0000.0,K,D*26
$SDDPT,001.5,+0.1*79
$SDDBT,005.1,f,001.5,M,000.8,F*0D

**Comment by marcelrv** [comment]
> we are on the way to rework the OpenSeaMap software. Thats why I’m looking to close the issue list as good as possible.

do you expect significant changes in the upload track logic with the update?
I was trying to make some sort of automated upload from signalK. 
But if the rest inferface will change significantly I'll await the changes.

**Comment by wldlzi** [comment]
you can see a first test-version at https://testdepth.openseamap.org/static/src/local_index.html So far, the new backend is very close to the old Java backend, but now implemented with django and python3.If you like to see aditional functionality, than this is the time to know about.regards Richard Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Marcel ***@***.***> Datum: 19.05.21  11:53  (GMT+01:00) An: OpenSeaMap/depth_webfrontend ***@***.***> Cc: Richard ***@***.***>, State change ***@***.***> Betreff: Re: [OpenSeaMap/depth_webfrontend] Always get processing error. Is it
  possible to see more details what goes wrong (#230) 



we are on the way to rework the OpenSeaMap software. Thats why I’m looking to close the issue list as good as possible.



do you expect significant changes in the upload track logic with the update?

I was trying to make some sort of automated upload from signalK.

But if the rest inferface will change significantly I'll await the changes.
