### ISSUE TITLE
single track view is not working

### ISSUE THREAD

**Issue by stevo01** [OpenSeaMap/depth_webfrontend#237]
The user @Nautic reported following error:

Each data donor has a list of their uploaded files ("Tracks" menu).
If he clicks on an ID there, this track is displayed on the map.

In my case, only a pink area with a coordinate system appears.

Maybe something is wrong with the sea mark layer?
Or with the water depth layer?

**Comment by stevo01** [comment]
sample url: https://depth.openseamap.org/singletrack.html?track_id=127587&zoom=12&lat=52.37155&lon=12.9525185

Analysis shows that call of mapserv.fcgi fail. 
https://depth.openseamap.org/cgi-bin/mapserv.fcgi?LAYERS=trackpoints_single_track_10&NUMZOOMLEVELS=22&PROJECTION=EPSG%3A900913&TYPE=png&TRANSPARENT=TRUE&TRACK_ID=127587&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A900913&BBOX=1408887.3051562,6859727.0816042,1448023.0636328,6898862.8400808&WIDTH=1024&HEIGHT=1024

proposal: replace the call of mapserver with a call of geoserver

**Comment by wschildbach** [comment]
The sample URL shows the map and track points now. Is that what is expected, i.e. is the bug fixed?

**Comment by wschildbach** [comment]
#240 fixed the pink area -- the correct server is now called up. It does appear that track filtering is not yet correct though. According to @martinover , https://depth.openseamap.org/singletrack.html?CQL_FILTER=TRACK_ID=127587&zoom=12&lat=52.37155&lon=12.9525185 should show a single filtered track.

**Comment by stevo01** [comment]
> The sample URL shows the map and track points now. Is that what is expected, i.e. is the bug fixed?

@wschildbach: I checked the feature and it seems to be fixed. Thanks for support.
