### ISSUE TITLE
Precision of position data

### ISSUE THREAD

**Issue by vk45** [OpenSeaMap/depth_webfrontend#25]
There was a remark from Jens that uploaded data from Sweden do not have the nedded precision of the position which is needed for processing.
What is the reason and could it be changed?

**Comment by jot4p** [comment]
> I have recorded data for 10 seconds from the A50 in three formats:
> 
> 1. raw_actisense which I can read with the actisense ebl-Reader
> 2. output of the canboat actisense-serial
> 3. json data , extracted by canboat analyzer from the actisense-serial
> 
> This a line right from the end of the json-file: {"timestamp":"2013-10-17-19:40:04.333","prio":"3","src":"160","dst":"255","pgn":"129029","description":"GNSS Position Data","fields":{"SID":"165","Date":"2013.10.17", "Time": "19:40:03.08580","Latitude":"51.4427608","Longitude":"06.9606460","GNSS type":"GPS","Method":"GNSS fix","Integrity":"No integrity checking","Number of SVs":"5","HDOP":"2.20","PDOP":"-0.01","Geoidal Separation":"-0.01","Reference Station ID":"15"}}
> 
> The times differ, the timestamp is made from the raspberry time. Time comes from the gps.
> 
> The elb-reader can open and display the raw file. Line 174 tells: Raw BST Data: 0x93,0x36,0x03,0x05,0xF8,0x01,0xFF,0xA0,0x49,0x8E,0x07,0x00,0x2B,0xA5,0x7B,0x3E,0xB4,0xCF,0x33,0x2A,0x00,0x70,0x7E,0x15,0x2F,0x9D,0x23,0x07,0x00,0x58,0x5F,0xE2,0xB4,0x4A,0xF7,0x00,0xE0,0xC1,0x08,0x05,0x00,0x00,0x00,0x00,0x10,0xFC,0x05,0xDC,0x00,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x00,0x34, Basic Message PGN: 129029 (0x1F805), SRC = 160, DST = 255, Priority = 3, Len = 43, Data = A5 7B 3E B4 CF 33 2A 00 70 7E 15 2F 9D 23 07 00 58 5F E2 B4 4A F7 00 E0 C1 08 05 00 00 00 00 10 FC 05 DC 00 FF FF FF FF FF FF 00
> 
> Full decoded Message NMEA 2000 PGN: 129029 (0x1F805) Name: GNSS Position Data Source = 160, Destination = 255 Priority = 3, Length = 43 Number Of Fields = 18 Field 1: SID = 165 Field 2: Position date = 17/10/2013 Field 3: Position time = 19:40:03.858 Field 4: Latitude = 51° 26.565648' N (51.4427608000000000°) Field 5: Longitude = 06° 57.638760' E (6.9606460000000000°) Field 6: Altitude = 84.460000 Metres Field 7: Type of System = 0 (GPS) Field 8: Method, GNSS = 1 (GNSS Fix) Field 9: Integrity = 0 Field 10: Reserved field Field 11: Number of SVs = 5 Field 12: HDOP = 2.20 Ratio Field 13: PDOP = -0.01 Ratio Field 14: Geoidal Separation = -0.01 Metres Field 15: Number of Reference Stations = 0
> 
> I see no difference in the resolution of the json and the ebl-Data. "Latitude":"51.4427608","Longitude":"06.9606460"
> 
> If I convert to a RMC messsage with my software I put out LAT=51° 26.565' N, LON =06° 57.638' E. This format is equivalent to the nmea0183 on the serial port. Is there a difference in the resolution with nmea2000 or nmea0183?
> 
> Am 17.10.2013 01:31, schrieb cleanerx:
> 
> > depends on what is most easily debugable.
> > If I had the actisense data I would replay it through my software and
> > halt the debugger at the parts of the code where the position is analyzed.
> > —
> > Reply to this email directly or view it on GitHub
> > [#25 (comment)](https://github.com/OpenSeaMap/depth_webfrontend/issues/25#issuecomment-26468218).

Hi, 
How it's possible to convert this:
A57B3EB4CF332A00707E152F9D230700585FE2B44AF700E0C108050000000010FC05DC00FFFFFFFFFFFF00

To this  ? 
{
"SID":"165"
"Date":"2013.10.17"
"Time":"19:40:03.08580"
"Latitude":"51.4427608"
"Longitude":"06.9606460"
"GNSStype":"GPS"
"Method":"GNSS fix"
"Integrity":"No integritychecking"
"Number of SVs":"5"
"HDOP":"2.20"
"PDOP":"-0.01"
"GeoidalSeparation":"-0.01"
"Reference Station ID":"15"
}

A5 hex > 165 dec
But the others? 
Based on NMEA is 8 bytes + 16 (date) + 32 (time) + 64 (lat), + 64 (lon)..

But it's impossible to convert... Ca you help me ?
