### ISSUE TITLE
In registration page, language of country and "language" do not match

### ISSUE THREAD

**Issue by wschildbach** [OpenSeaMap/depth_webfrontend#91]
Country names are all in english, yet langage names are in different languages. It would be useful to have them both the same. Additionally, it is probably not useful to offer choices that the project does not intend to support.

**Comment by wldlzi** [comment]
the version of the handlebar library does not support your request. Even if you are true for the field country, many, many other fields and pages offer the two supported languages.
Therefore I close this issue for now
