### ISSUE TITLE
Track upload interface gives no warning if vessel profile is not available

### ISSUE THREAD

**Issue by wschildbach** [OpenSeaMap/depth_webfrontend#95]
In http://depth.openseamap.org/#tracks, if there is no vessel profile selected, upload should not be possible (at the moment, I can try to upload but the upload seems to fail).

Additionally, it would be useful to provide a link to the "add vessel" page, specifically if no vessel profile is available at all.

**Comment by wldlzi** [comment]
this bug belongs to history
