### ISSUE TITLE
Enhancement: Indicate that preprocessing of files is not immediate.

### ISSUE THREAD

**Issue by wschildbach** [OpenSeaMap/depth_webfrontend#99]
When I upload one or more tracks, and go to "tracks viewer" right afterwards, my tracks are not shown. It would be helpful if the webpage could mention that there will be a time lag after uploading.

**Comment by aAXEe** [comment]
Is there a way for the front-end to query the processing-enabled state?
If processing in disabled we should place a warning or notification on the site. This could be accomplished by adding a status entry in the back-end (api2/status ?).

**Comment by cleanerx** [comment]
No the processing is realized as cronjob.
